site_name: Magma
repo_url: https://github.com/Plethan/Magma
repo_name: Plethan/Magma

theme:
  name: "material"
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - header.autohide

  icon:
    repo: fontawesome/brands/github


  font:
    text: Lato
    code: Roboto Mono
  palette:
    primary: white
    accent: 'Light Blue'

nav:
  - home: index.md
  - Basics:
    - Gems: Basics/Gems.md
    - Listener: Basics/Listeners.md
    - ReGem: Basics/ReGem.md

markdown_extensions:
 - pymdownx.highlight
 - pymdownx.superfences

